# Default values for any settings 
defaults:
  articles:
    keywords:
      rotation_mode: "equal" # Todo: Finish the JS logic that uses this
    share:
      title: "Default Title"
      summary: "Default Summary"
      href: "#Default-Href"
      networks:
        - "facebook"
        - "twitter"
        - "googleplus"
        - "pinterest"
        - "linkedin"
        - "stumbleupon"
    export:
      formats:
        - "pdf"
        - "docx"
# There are some Jade/Pug mixins that show details via HTML comments, 
# these controls what those display
verbosity:
  all: true
  include: true
# Limits for any setting
limits:
  articles:
    title: 
      min: 10
      max: 40
    summary:
      max: 80
  keywords:
    tags: 7
    categories: 7
    max_global: